services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: sistemafime_postgres_dev
    environment:
      POSTGRES_DB: sistemafime_db
      POSTGRES_USER: sistemafime_user
      POSTGRES_PASSWORD: sistemafime_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - sistemafime_network_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sistemafime_user -d sistemafime_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Aplicación ASP.NET Core para desarrollo
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sistemafime_web_dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=sistemafime_db;Username=sistemafime_user;Password=sistemafime_password
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=true
    volumes:
      # Montar el código fuente para hot reload
      - .:/app
      - /app/bin
      - /app/obj
      - dotnet_packages:/root/.nuget/packages
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sistemafime_network_dev
    restart: unless-stopped
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:
  dotnet_packages:

networks:
  sistemafime_network_dev:
    driver: bridge